version: 2.0

#orbs:
#  aws-ecr: circleci/aws-ecr@6.9.1
#  aws-ecs: circleci/aws-ecs@1.2.0

jobs:
  build:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
        environment:
          DATABASE_URL: postgresql://postgres@localhost/
          DATABASE_URL_DB: postgresql://postgres@localhost/dvdrental
      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - run: |
          psql \
          -d $DATABASE_URL \
          -p 5432 \
          -U postgres \
          -c "create database dvdrental;"
      - run: |
          pg_restore \
          -d $DATABASE_URL_DB \
          -p 5432 \
          -U postgres \
          ./docker/db/script/dvdrental.tar
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Install dependencies
          command: ./gradlew generateTablesJooqSchemaSource
      - run:
          name: Install dependencies
          command: ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: workspace
          paths:
            - .
#  image-build-and-deploy:
#    steps:
#      - aws-ecr/build-and-push-image:
#          dockerfile: Dockerfile
#          repo: ${MY_APP_PREFIX}
#          tag: '${CIRCLE_SHA1}'
#      - asws-ecs/deploy-service-update:
#          requires:
#            - aws-ecr/build-and-push-image
#          family: '${MY_APP_PREFIX}-service'
#          cluster-name: '${MY_APP_PREFIX}-cluster'
#          container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
#      - image-build-and-deploy:
#          requires:
#            - build